Bicaws 2755 triggers and exceptions sidebar
ministryofjustice/bichard7-next-ui pull request #238
Opened 2023-04-24 08:58 UTC by emadkaramad

2023-04-24 14:47 UTC, C-gyorfi commented on src/utils/getTriggerInfo/triggers.json
Nice one extracting the info into JSON. Would it make sense to add this to the data repo? We have[ trigger definitions there](https://github.com/ministryofjustice/bichard7-next-data/blob/main/output-data/data/trigger-definitions.json) with slightly different descriptions:

2023-04-24 14:58 UTC, emadkaramad commented on src/utils/getTriggerInfo/triggers.json
Good shout! Yeah, it makes sense to move both triggers and exceptions file to data repo. I'll do that in a separate PR.

2023-04-24 15:08 UTC, agnieszkazbikowska-madetech requested changes
Nice one! It's a big piece of work. I left a few comments but very minor.

2023-04-24 15:08 UTC, agnieszkazbikowska-madetech commented on src/components/ActionLink.tsx
> +const ActionLink: React.FC<Props> = ({ children, className, onClick }) => {
You could do `const ActionLink = ({ children, className, onClick }: Props) => {` here, it might be easier to read? Tbh it's a preference thing.

2023-04-24 15:08 UTC, agnieszkazbikowska-madetech commented on src/features/CourtCaseDetails/CourtCaseDetails.tsx
> +const sideBarWidth = "364px"
I like this! This way we don't have any magic numbers.

2023-04-24 15:08 UTC, agnieszkazbikowska-madetech commented on src/features/CourtCaseDetails/Sidebar/Exceptions.tsx
> +const Exceptions: React.FC<Props> = ({ aho }) => {
We can write it the other way (I've added a comment above) & avoid using `React.FC`.

2023-04-24 15:08 UTC, agnieszkazbikowska-madetech commented on src/features/CourtCaseDetails/Sidebar/TriggersAndExceptions.tsx
> +const TriggersAndExceptions: React.FC<Props> = ({ courtCase, aho }) => {
We can write it the other way (I've added a comment above) & avoid using `React.FC`.

2023-04-24 16:45 UTC, emadkaramad commented on src/features/CourtCaseDetails/Sidebar/Triggers.tsx
> +    const checkBox = event.target as HTMLInputElement
ChangeEvent is a generic type. We can pass the HTML element type to it:
`ChangeEvent<HTMLInputElement>`

2023-04-25 07:50 UTC, agnieszkazbikowska-madetech approved these changes

2023-04-25 11:33 UTC, merged